version: '3.8'

services:
  text-to-sql-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=phpmyadmin
      - MYSQL_PASSWORD=StrongPasswordHere!
      - MYSQL_DATABASE=org_insights
    volumes:
      - ../data:/app/data
      - ../models:/app/models
      - ../logs:/app/logs
    depends_on:
      - mysql
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=StrongPasswordHere!
      - MYSQL_DATABASE=org_insights
      - MYSQL_USER=phpmyadmin
      - MYSQL_PASSWORD=StrongPasswordHere!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: